Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Modules\Core\Http\Controllers\Auth\EmailVerificationController;
use Modules\Core\Http\Controllers\Auth\LogoutController;
use Modules\Core\Http\Controllers\DepartmentsController;
use Modules\Core\Http\Controllers\FileController;
use Modules\Core\Http\Controllers\NotificationController;
use Modules\Core\Http\Controllers\OptionsController;
use Modules\Core\Http\Controllers\PermissionsController;
use Modules\Core\Http\Controllers\RolesController;
use Modules\Core\Http\Controllers\UserAddressesController;
use Modules\Core\Http\Controllers\UsersController;
use Modules\Core\Http\Livewire\Auth\Login;
use Modules\Core\Http\Livewire\Auth\Passwords\Confirm;
use Modules\Core\Http\Livewire\Auth\Passwords\Email;
use Modules\Core\Http\Livewire\Auth\Passwords\Reset;
use Modules\Core\Http\Livewire\Auth\Register;
use Modules\Core\Http\Livewire\Auth\Verify;

Route::middleware('guest')->group(function () {
    Route::get('login', Login::class)->name('login');
    Route::get('register', Register::class)->name('register');
});

Route::get('password/reset', Email::class)->name('password.request');
Route::get('password/reset/{token}', Reset::class)->name('password.reset');

Route::middleware('admin:core')->group(function () {
    Route::get('email/verify', Verify::class)->middleware('throttle:6,1')->name('verification.notice');
    Route::get('password/confirm', Confirm::class)->name('password.confirm');
    Route::get('email/verify/{id}/{hash}', EmailVerificationController::class)->middleware('signed')->name('verification.verify');

    Route::post('logout', LogoutController::class)->name('logout');

    Route::view('/', 'core::index')->name('home');
    Route::view('/dashboard', 'core::dashboard')->name('dashboard');

    // file
    Route::get('/md', [FileController::class, 'md'])->name('file.md');

    // optios
    Route::group(['prefix' => 'option', 'as' => 'option.'], function(){

        Route::get('/', [OptionsController::class, 'index'])->name('index');
        Route::post('/', [OptionsController::class, 'store']);
    });

    // 消息管理
    Route::get('/notification', [NotificationController::class, 'index'])->name('notification.index');

    // 权限管理
    Route::post('permission/attach', [PermissionsController::class, 'attach'])->name('permission.attach');
    Route::resource('permission', PermissionsController::class);
    Route::resource('roles', RolesController::class);

    Route::match(['get', 'post'], 'users/profile', [UsersController::class, 'profile'])->name('user.profile');
    Route::match(['get', 'post'], 'users/resetpasswd', [UsersController::class, 'resetpasswd'])->name('user.resetpasswd');

    Route::resource('users', UsersController::class);
    Route::resource('departments', DepartmentsController::class);
    Route::resource('user-addresses', UserAddressesController::class);
});

Models/User.php
<?php

namespace Modules\Core\Models;

use App\Models\BaseModel;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Notifications\Notifiable;
use Modules\Core\Http\Filters\DepartmentFilter;
use Modules\Core\Http\Filters\RoleFilter;
use Spatie\Permission\Traits\HasRoles;
use Stancl\Tenancy\Database\Concerns\BelongsToTenant;
use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends BaseModel implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use HasFactory;
    use Notifiable;
    use BelongsToTenant;
    use HasRoles;
    // use HasSocial; // 社交模块
    // use MustVerifyEmail; 邮箱验证
    use Authenticatable, Authorizable, CanResetPassword;

    protected $table = 'core_users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'mobile','mobile_verified_at','create_ip_at', 'tenant_id',
        'last_login_at','last_login_ip_at','login_times','status','nickname','avatar', 'username', 'is_admin', 'level'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'mobile_verified_at' => 'datetime',
        'is_admin' => 'boolean'
    ];

    /**
     * @return string[]
     */
    protected function filters()
    {
        return [
            'depart_id' => DepartmentFilter::class,
            'role_id' => RoleFilter::class,
        ];
    }

    /**
     * 获取用户姓名
     * 优先级 username => nickname => name
     * @return mixed
     */
    public function getName($mobileFirst = false)
    {
        return $this->mobile&&$mobileFirst
            ? $this->mobile
            : ($this->username ?: ($this->nickname ?: ( $this->name ?: '' )));
    }

    /**
     * @return bool
     */
    public function isSuper()
    {
        return true;
    }

    protected static function boot()
    {
        parent::boot();
        static::creating(function ($model) {
            $model->create_ip_at = $model->create_ip_at ?? request()->ip();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function departments()
    {
        return $this->belongsToMany(Department::class, 'core_department_user');
    }
}

Http/Controllers/Api/UsersController.php
<?php
/**
 * Created by PhpStorm.
 * User: jory
 * Date: 2019/4/3
 * Time: 18:21
 */

namespace Modules\Core\Http\Controllers\Api;


use Illuminate\Http\Request;
use Modules\Core\Exports\UsersExport;
use Modules\Core\Http\Controllers\BaseController;
use Modules\Core\Http\Resources\UserResource;
use Modules\Core\Models\User;

class UsersController extends BaseController
{

    protected $model;

    /**
     * UsersController constructor.
     * @param UserRepository $model
     */
    public function __construct(User $model)
    {
        $this->model = $model;
    }

    /**
     * @param Request $request
     * @return mixed
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function index(Request $request)
    {
        $limit = $request->get('search') ? 100 : \request('limit', 10);
        $users = $this->model->filter($request)->paginate($limit);

        return $this->toCollection($users, UserResource::class);
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function export(Request $request)
    {
        $request->validate(['ids' =>'required']);
        $field = [
            'id' => 'USERID',
            'name' => '姓名',
            'mobile' => '电话',
            'created_at' =>'入职时间'
        ];
        return $this->toAjaxExport(new UsersExport($request, ['field' => $field]));
    }
}

Http/Controllers/UsersController.php
<?php

namespace Modules\Core\Http\Controllers;

use Modules\Core\Http\Controllers\BaseController;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Modules\Core\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Modules\Core\Http\Requests\UserRequest;
use Modules\Core\Http\Resources\UserResource;
use Illuminate\Validation\ValidationException;

/**
 * Class UsersController.
 *
 * @package namespace Modules\Core\Http\Controllers;
 */
class UsersController extends BaseController
{
    /**
     * @var User
     */
    protected $model;

    public function __construct(User $model)
    {
        $this->model = $model;
    }


    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|mixed
     */
    public function index(Request $request)
    {
        if($request->expectsJson()) {
            $users = $this->model->filter($request)->paginate($request->get('limit', 15));
            return $this->toCollection($users, UserResource::class);
        }
        return view('core::users.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
         $this->authorize('create', User::class);
        return view('core::users.create');
    }


    /**
     * @param UserRequest $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request)
    {
        try {
            if($request->get('password')) {
                $request->merge(['password' => Hash::make($request->get('password'))]);
            }else{
                unset($request['password']);
            }
            $user = $this->model->create($request->all());

            $user->departments()->attach($request->get('department'));

            return redirect()->back()->with('status', 'success');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->model->with([
            'organizations:name,oid',
            'departments:name,level',
            'address:id,province,city,address,contact_name,contact_phone'
        ])->find($id);

        // $this->authorize('view', $user);
        return $this->toTable($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->model->find($id);
        // $this->authorize('update', $user);

        return view('core::users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UserUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *

     */
    public function update(UserRequest $request, $id)
    {
        try {
            $model = $this->model->find($id);
            // $this->authorize('update', $model);

            if($request->get('password')) {
                $request->merge(['password' => Hash::make($request->get('password'))]);
            }else{
                unset($request['password']);
            }

            $model->fill($request->all())->save();

            $model->addFromMediaLibraryRequest($request->get('avatar'))->toMediaCollection('avatar');

            // 更新部门
            $depart = $model->departments();
            $depart->detach();
            $depart->attach($request->get('department'));

            return redirect()->back()->with('status', 'update success');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);
        $this->authorize('delete', $model);
        $model->delete($id);

        return $this->toResponse([], '删除成功');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function profile(Request $request)
    {
        $user = auth()->user();
        if($request->isMethod('post')) {
            $model = $this->model->where('id', $user->id)->first();
            $model->fill($request->except('password'))->save();
        }

        return view('core::users.profile', compact('user'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function resetpasswd(Request $request)
    {
        $user = auth()->user();
        if($request->isMethod('post')) {
            $request->validate(['password' => 'required', 'oldpasswd' => 'required', 'password_confirmation' => 'required']);
            $userModel = $this->model->where('id', $user->id)->first();
            $pass = true;
            $message = '';

            if($request->get('password') != $request->get('password_confirmation')) {
                $pass = false;
                $message = '两次密码输入不一致';
            }
            if(!Auth::guard()->validate(['email' => $userModel->email, 'password' => $request->get('oldpasswd')])){
                $pass = false;
                $message = '旧密码输入错误';
            }

            if($pass) {
                $userModel->fill([
                    'password' => Hash::make($request->get('password')),
                    'remember_token' => Str::random(60)
                ])->save();
                return redirect()->back()->with('status', 'success');
            }else{
                return redirect()->back()->with('status', $message);
            }
        }

        return view('core::users.resetpasswd', compact('user'));
    }
}

Resources/views/users/create.blade.php
@extends('core::layouts.modal')

@section('content')
    <x-wd-card>
        <x-wd-form :action="route('users.store')" method="post" >
            @include('core::users.fields')
        </x-form>
    </x-card>
@endsection

@push('script')
    <script>
        layui.use('form', function(){
            var form = layui.form

            form.verify({
                title: function(value){
                    if(value.length < 5){
                        return '标题至少得5个字符啊';
                    }
                }
                ,pass: [/(.+){6,12}$/, '密码必须6到12位']
                ,content: function(value){
                    layedit.sync(editIndex);
                }
            })

            form.on('submit(component-form-demo1)', function(data){
                // parent.layer.alert(JSON.stringify(data.field), {
                //     title: '最终的提交信息'
                // })
                return true;
            });
        })
    </script>
@endpush

Resources/views/users/edit.blade.php
@extends('core::layouts.master')

@section('content')
    <x-wd-card>
        <x-wd-form :action="route('users.update', $user->id)" method="patch">
            @include('core::users.fields')
        </x-form>
    </x-card>
@endsection

Resources/views/users/fields.blade.php
<x-wd-formItem label="{{ __('main.name') }}">
<x-wd-input name="name" :value="$user->name??''" label="name" required></x-input>
</x-wd-formItem>

<x-wd-formItem label="{{ __('main.department') }}">
<x-wd-input.select name="department" :value="$user->department??''" :optionHtml="\Modules\Core\Models\Department::getOptionsHtml(isset($user->departments[0])?$user->departments[0]->id:0)" label="department" required>
</x-input.select>
</x-wd-formItem>

<x-wd-formItem label="{{ __('main.mobile') }}">
<x-wd-input name="mobile" :value="$user->mobile??''" label="mobile" required></x-input>
</x-wd-formItem>

<x-wd-formItem label="{{ __('main.email') }}">
<x-wd-input type="email" name="email" :value="$user->email??''" label="email" required></x-input>
</x-wd-formItem>

<x-wd-formItem label="{{ __('avatar') }}">
    <input type="file" name="avatar">
</x-wd-formItem>

<x-wd-formItem label="{{ __('main.password') }}">
<x-wd-input type="password" name="password" label="password"></x-input>
</x-wd-formItem>


<div class="layui-form-item layui-layout-admin">
    <div class="layui-input-block">
		<div class="layui-footer z-50" style="left:0;">
			<button class="layui-btn" lay-submit lay-filter="component-form-demo1">{{__('submit')}}</button>
			<button type="reset" class="layui-btn layui-btn-primary" lay-submit-cancel>{{__('cancel')}}</button>
		</div>
    </div>
</div>

@push('script')
	<script>
		layui.use('form', function(){
			var form = layui.form
		})
	</script>
@endpush

Resources/views/users/index.blade.php
@extends('core::layouts.column_left')

@section('leftside')
    <div class="layui-tab" lay-filter="user_tab">
        @if(Modules\Core\Models\Department::count() > 0)
            <ul class="layui-tab-title">
                <li class="layui-this">部门</li>
                <li>角色</li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show"><div id="depart_tree"></div></div>
                <div class="layui-tab-item"><div id="role_tree"></div></div>
            </div>
        @else
            <ul class="layui-tab-title">
                <li class="layui-this">角色</li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show"><div id="role_tree"></div></div>
            </div>
        @endif
    </div>
@stop

@section('content')
    <x-wd-submenu :items="
        [
            ['name' => '全部人员', 'uri'=>'javascript:;', 'on'=>true]
       ]" />

    @if(Modules\Core\Models\Department::count() > 0)
        <div id="depart_user">
            <table  id="user_depart_table" lay-filter="user_depart_table"></table>
        </div>
        <div id="role_user" style="display: none;">
            <div class="tip py-4">请点击左侧角色进行人员管理操作</div>
            <table  id="user_role_table" lay-filter="user_role_table"></table>
        </div>
    @else
        <div id="role_user">
            <div class="tip py-4">请点击左侧角色进行人员管理操作</div>
            <table id="user_role_table" lay-filter="user_role_table"></table>
        </div>
    @endif

@endsection


@push('script')
    <script type="text/html" id="ticket_process">
        <div class="layui-progress" lay-showPercent="yes">
            <div class="layui-progress-bar layui-bg-red" lay-percent="10%"></div>
        </div>
    </script>

    <script>
        layui.extend({
            pickerUser: 'modules/picker/picker_user'
        }).use(['table', 'element', 'tree', 'pickerUser', 'admin'], function(){
            var table = layui.table,
                admin = parent.layui == layui?layui.admin:parent.layui.admin,
                tree = layui.tree,
                pickerUser = layui.pickerUser,
                element = layui.element;

            var currentUrl = '{!! URL::full() !!}',
                $department_tree = $("#depart_tree"),
                $role_tree = $("#role_tree"),
                depart_id = 0,
                $title = $("#J_subtitle").find("li.layui-this > a")
                role_id = '';

            if($("#user_depart_table").length > 0) {
                table.render({
                    elem: '#user_depart_table',
                    url: '{!! URL::full() !!}',
                    where: {'orderBy': 'created_at', 'sortedBy': 'desc'},
                    autoShow: '{{ route('users.show', '_id_') }}',
                    page: true,
                    canSearch: true,
                    toolbar: {!! Auth::user()->can('admin', \Modules\Core\Models\User::class)?'"default"':'[]' !!},
                    height: 'full-110',
                    export: {url: '{{ url('/api/users/export') }}', can: true, all: true},
                    cols: [
                        [
                            {"type":"checkbox",width:80,"fixed":"left"},
                            {"field":"id","title":"员工ID",width:80,"fixed":"left"},
                            {"field":"name","title":"姓名",width: 250},
                            {"field":"mobile","title":"电话",width: 250},
                            {"field":"email","title":"邮箱"},
                            {"field":"updated_at","title":"更新时间",width:160}
                        ]
                    ]
                });


                //监听行工具事件
                table.on('toolbar(user_depart_table)', function(obj){
                    var checked = table.checkStatus('user_depart_table');

                    if(obj.event == 'create') {
                        admin.openModal('{{ route('users.create') }}', '新增数据')
                        return true;
                    }

                    if((obj.event == 'delete'|| obj.event == 'update') && checked.data.length >0 ) {
                        if(checked.data.length !== 1) {
                            layer.msg('请选择一条数据!');
                            return false;
                        }

                        if(obj.event === 'delete') {
                            layer.confirm('真的删除行么', function(index){
                                layui.util.request.post('{{ route('users.destroy', '_id_') }}'.replace('_id_', checked.data[0].id), {'_method': 'DELETE'}, function(res){
                                    layer.msg('删除成功');
                                    table.reload('user_depart_table')
                                })

                                layer.close(index);
                            });
                        }else if(obj.event === 'update') {
                            admin.openModal('{{route('users.edit', '_id_')}}'.replace('_id_', checked.data[0].id), '更新数据')
                            return true;
                        }
                    }
                });

                // 部门树
                tree.render({
                    elem: '#depart_tree',
                    onlyIconControl: true,
                    data:  @json(\Modules\Core\Models\Department::getTree(2, 'users', true)),
                    click: function(obj){
                        var data = obj.data

                        $title.text(data.text)
                        table.reload("user_depart_table", {
                            url: currentUrl,
                            where: {'depart_id': data.id},
                            page: {curr: 1}
                        })
                    }
                });
            }

            tree.render({
                elem: '#role_tree',
                onlyIconControl: true,
                data: @json(\Modules\Core\Models\Role::getTree(1, 'web')),
                click: function(obj){
                    role_id = obj.data.id
                    $title.text(obj.data.text)
                    $("#role_user").find(".tip").hide();

                    // 角色树
                    table.render({
                        elem: '#user_role_table',
                        url: '{!! URL::full() !!}',
                        where: {'orderBy': 'created_at', 'sortedBy': 'desc', 'role_id': role_id, 'curr': 1},
                        page: true,
                        canSearch: true,
                        height: 'full-110',
                        toolbar: ['create', 'delete'],
                        cols: [
                            [
                                {"type":"checkbox",width:80,"fixed":"left"},
                                {"field":"id","title":"ID",width:80,"fixed":"left"},
                                {"field":"name","title":"name",width: 350},
                                {"field":"mobile","title":"电话",width: 350},
                                {"field":"email","title":"email"},
                                {"field":"updated_at","title":"更新时间",width:160,off:false}
                            ]
                        ]
                    });
                }
            });

            table.on('toolbar(user_role_table)', function(obj){
                var checkStatus = table.checkStatus(obj.config.id);
                switch(obj.event){
                    case 'delete':
                        var data = checkStatus.data;
                        if(data.length < 1) {
                            layer.msg('请选择数据');
                        }
                        var ids = data.map(function (item) {
                            return item.id;
                        });
                        layui.util.request.post('{{ url('/api/roles/detach') }}', {'role_id': role_id, 'ids': ids.join(',')}, function(res){
                            table.reload("user_role_table")
                        })

                        break;
                    case 'create':
                        if(role_id == '') {
                            layer.msg('请选择角色');
                            return;
                        }
                        pickerUser.render({
                            done: function(res, $el) {
                                layer.close($el)
                                var ids = res.map(function (item) {
                                    return item.id;
                                });
                                layui.util.request.post('{{ url('/api/roles/attach') }}', {'role_id': role_id, 'ids': ids.join(',')}, function(res){
                                    table.reload("user_role_table")
                                })
                            }
                        })
                        // layer.msg(checkStatus.isAll ? '全选': '未全选');
                        break;
                };
            });

            // tab
            element.on('tab(user_tab)', function(data){
                if(data.index == 0) {
                    $("#role_user").hide()
                    $("#depart_user").show();
                    $title.text('全部人员')
                }else{
                    $title.text('角色管理')
                    $("#depart_user").hide()
                    $("#role_user").show()
                }
            });
        });
    </script>
@endpush

Resources/views/users/profile.blade.php
@extends('core::layouts.master')

@section('content')
    <x-wd-submenu :items="
        [
            ['name' => '基本资料', 'url' => route('user.profile'),'on'=>true],
            ['name' => '修改密码', 'url' => route('user.resetpasswd')],
       ]" />

    <div class="layui-card">
        <div class="layui-card-body">
            <form class="layui-form" id="layuiadmin-form-useradmin" method="post" actio="{{ route('user.profile') }}">
                @csrf
                <div class="layui-form-item">
                    <label class="layui-form-label">UserID</label>
                    <div class="layui-input-inline">
                        <input type="text" disabled autocomplete="off" class="layui-input" value="{{ Auth::user()->id }}">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">用户名</label>
                    <div class="layui-input-inline">
                        <input type="text" name="name" lay-verify="required" placeholder="请输入用户名" autocomplete="off" class="layui-input" value="{{ Auth::user()->name }}">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">邮箱</label>
                    <div class="layui-input-inline">
                        <input type="text" name="email" lay-verify="email" placeholder="请输入邮箱" autocomplete="off" class="layui-input" value="{{ Auth::user()->email }}">
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">手机号码</label>
                    <div class="layui-input-inline">
                        <input type="text" name="mobile" placeholder="请输入号码" autocomplete="off" class="layui-input" value="{{ Auth::user()->mobile }}">
                    </div>
                </div>

                <div class="layui-form-item layui-layout-admin">
                    <div class="layui-input-block">
                        <div class="layui-footer z-50" style="left:0;">
                            <button class="layui-btn" lay-submit lay-filter="core_user_profile">{{__('submit')}}</button>
                            <button type="reset" class="layui-btn layui-btn-primary">{{__('cancel')}}</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

@push('script')
    <script>
        layui.use('form', function(){
            var form = layui.form;
        })
    </script>
@endpush

Resources/views/users/show.blade.php
@extends('core::layouts.modal')

@section('content')
    <div class="row" style="padding-left: 20px">
        <table class="table table-hover table-bordered">
            <tbody>
				<tr><td>{{ __("field.id") }}</td><td>{!! $user->id !!}</td></tr>
				<tr><td>{{ __("field.name") }}</td><td>{!! $user->name !!}</td></tr>
				<tr><td>{{ __("field.email") }}</td><td>{!! $user->email !!}</td></tr>
				<tr><td>{{ __("field.email_verified_at") }}</td><td>{!! $user->email_verified_at !!}</td></tr>
				<tr><td>{{ __("field.password") }}</td><td>{!! $user->password !!}</td></tr>
				<tr><td>{{ __("field.remember_token") }}</td><td>{!! $user->remember_token !!}</td></tr>
				<tr><td>{{ __("field.created_at") }}</td><td>{!! $user->created_at !!}</td></tr>
				<tr><td>{{ __("field.updated_at") }}</td><td>{!! $user->updated_at !!}</td></tr>
			</tbody>
        </table>
    </div>
@endsection

Resources/views/users/table.blade.php
<div class="table-responsive">
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
				<th>{{ __('main.id') }}</th>
				<th>{{ __('main.name') }}</th>
				<th>{{ __('main.email') }}</th>
				<th>{{ __('main.email_verified_at') }}</th>
				<th>{{ __('main.password') }}</th>
				<th>{{ __('main.remember_token') }}</th>
				<th>{{ __('main.created_at') }}</th>
				<th>{{ __('main.updated_at') }}</th>
				<th><i class='fa fa-cogs'></i></th>
			</tr>
        </thead>
        <tbody>
        @foreach($users as $item)
            <tr>
				<td>{{ $item->id ?? "" }}</td>
				<td>{{ $item->name ?? "" }}</td>
				<td>{{ $item->email ?? "" }}</td>
				<td>{{ $item->email_verified_at ?? "" }}</td>
				<td>{{ $item->password ?? "" }}</td>
				<td>{{ $item->remember_token ?? "" }}</td>
				<td>{{ $item->created_at ?? "" }}</td>
				<td>{{ $item->updated_at ?? "" }}</td>
				<td>
					<form method="post" action="{{ route("users.destroy", $item->id) }}">
						<input type="hidden" name="_method" value="DELETE">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<div class="btn-group">
							<a class="btn btn-xs" title="查看" data-toggle="modal" data-position="fixed" href="{{ route("users.show", $item->id) }}"><i class="fa fa-eye"></i></a>
							<a class="btn btn-xs" title="编辑" data-toggle="modal" data-position="fixed" href="{{ route("users.edit", $item->id) }}"><i class="fa fa-edit"></i></a>
							<button type="submit" class="btn btn-xs btn-danger" onclick="return confirm('确认删除?')"><i class="fa fa-trash "></i></button>
						</div>
					</form>
				</td>
			</tr>
        @endforeach
        </tbody>
    </table>
    {{ $users->appends(request()->all())->links('__page') }}
</div>