Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Modules\Core\Http\Controllers\Auth\EmailVerificationController;
use Modules\Core\Http\Controllers\Auth\LogoutController;
use Modules\Core\Http\Controllers\DepartmentsController;
use Modules\Core\Http\Controllers\FileController;
use Modules\Core\Http\Controllers\NotificationController;
use Modules\Core\Http\Controllers\OptionsController;
use Modules\Core\Http\Controllers\PermissionsController;
use Modules\Core\Http\Controllers\RolesController;
use Modules\Core\Http\Controllers\UserAddressesController;
use Modules\Core\Http\Controllers\UsersController;
use Modules\Core\Http\Livewire\Auth\Login;
use Modules\Core\Http\Livewire\Auth\Passwords\Confirm;
use Modules\Core\Http\Livewire\Auth\Passwords\Email;
use Modules\Core\Http\Livewire\Auth\Passwords\Reset;
use Modules\Core\Http\Livewire\Auth\Register;
use Modules\Core\Http\Livewire\Auth\Verify;

Route::middleware('guest')->group(function () {
    Route::get('login', Login::class)->name('login');
    Route::get('register', Register::class)->name('register');
});

Route::get('password/reset', Email::class)->name('password.request');
Route::get('password/reset/{token}', Reset::class)->name('password.reset');

Route::middleware('admin:core')->group(function () {
    Route::get('email/verify', Verify::class)->middleware('throttle:6,1')->name('verification.notice');
    Route::get('password/confirm', Confirm::class)->name('password.confirm');
    Route::get('email/verify/{id}/{hash}', EmailVerificationController::class)->middleware('signed')->name('verification.verify');

    Route::post('logout', LogoutController::class)->name('logout');

    Route::view('/', 'core::index')->name('home');
    Route::view('/dashboard', 'core::dashboard')->name('dashboard');

    // file
    Route::get('/md', [FileController::class, 'md'])->name('file.md');

    // optios
    Route::group(['prefix' => 'option', 'as' => 'option.'], function(){

        Route::get('/', [OptionsController::class, 'index'])->name('index');
        Route::post('/', [OptionsController::class, 'store']);
    });

    // 消息管理
    Route::get('/notification', [NotificationController::class, 'index'])->name('notification.index');

    // 权限管理
    Route::post('permission/attach', [PermissionsController::class, 'attach'])->name('permission.attach');
    Route::resource('permission', PermissionsController::class);
    Route::resource('roles', RolesController::class);

    Route::match(['get', 'post'], 'users/profile', [UsersController::class, 'profile'])->name('user.profile');
    Route::match(['get', 'post'], 'users/resetpasswd', [UsersController::class, 'resetpasswd'])->name('user.resetpasswd');

    Route::resource('users', UsersController::class);
    Route::resource('departments', DepartmentsController::class);
    Route::resource('user-addresses', UserAddressesController::class);
});

Http/Controllers/UserAddressesController.php
<?php

namespace Modules\Core\Http\Controllers;

use Modules\Core\Http\Controllers\BaseController;
use Illuminate\Http\Request;
use Modules\Core\Models\UserAddress;
use Illuminate\Validation\ValidationException;
use Modules\Core\Http\Requests\UserAddressRequest;
use Modules\Core\Http\Resources\UserAddressesResource;

/**
 * Class UserAddressesController.
 *
 * @package namespace Modules\Core\Http\Controllers;
 */
class UserAddressesController extends BaseController
{
    /**
     * @var UserAddress
     */
    protected $model;

    public function __construct(UserAddress $model)
    {
        $this->model = $model;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|mixed
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function index(Request $request)
    {
        if($request->expectsJson()) {
            $userAddresses = $this->model->paginate($request->get('limit', 15));
            return $this->toCollection($userAddresses, UserAddressesResource::class);
        }
        return view('core::userAddresses.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        // $this->authorize('create', UserAddress::class);
        return view('core::userAddresses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  UserAddressCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *

     */
    public function store(UserAddressRequest $request)
    {
        try {
            $userAddress = $this->model->create($request->all());

            return redirect()->back()->with('message', '新增操作成功');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $userAddress = $this->model->find($id);
        // $this->authorize('view', $userAddress);
        return $this->toTable($userAddress);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $userAddress = $this->model->find($id);
        // $this->authorize('update', $userAddress);

        return view('core::userAddresses.edit', compact('userAddress'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UserAddressUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *

     */
    public function update(UserAddressRequest $request, $id)
    {
        try {
            $model = $this->model->find($id);
            // $this->authorize('update', $model);

            $model->fill($request->all())->save();

            return redirect()->back()->with('message', '更新操作成功');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);
        // $this->authorize('delete', $model);
        $this->model->delet($id);
        return redirect()->back()->with('message', 'UserAddress deleted.');
    }
}

Resources/views/userAddresses/create.blade.php
@extends('core::layouts.master')

@section('content')

    <div class="layui-card layui-form">
        <div class="layui-card-header">新增</div>
        <div class="layui-card-body">
            <form action="{{ route('user-addresses.store') }}" method="post" class="layui-form ">
                {{ csrf_field() }}
                <input type="hidden" name="user_id" value="{{ !Auth::guest()?Auth::user()->id:0 }}">

                <div class="layui-row layui-col-space10 layui-form-item">
                    @include('core::userAddresses.fields')
                </div>
            </form>
        </div>
    </div>

@endsection

@push('script')
    <script>
        layui.use('form', function(){
            var form = layui.form


            form.on('submit(submit-form)', function(data){
                return true;
            });
        })
    </script>
@endpush

Resources/views/userAddresses/edit.blade.php
@extends('layouts.modal')

@section('content')
	<div class="layui-card layui-form">
		<div class="layui-card-header">编辑</div>
		<div class="layui-card-body">

			<form action="{{ route('user-addresses.update', $useraddress->id) }}" method="post" class="layui-form ">
					<input type="hidden" name="_method" value="patch" >
					{{ csrf_field() }}

					<div class="layui-row layui-col-space10 layui-form-item">
							@include('core::userAddresses.fields')
					</div>

			</form>

		</div>
	</div>

@endsection

Resources/views/userAddresses/fields.blade.php
@input(["name"=>"province","type"=>"text","value"=>$userAddress->province ?? ""])
@input(["name"=>"city","type"=>"text","value"=>$userAddress->city ?? ""])
@input(["name"=>"district","type"=>"text","value"=>$userAddress->district ?? ""])
@input(["name"=>"address","type"=>"text","value"=>$userAddress->address ?? ""])
@input(["name"=>"zip","type"=>"text","value"=>$userAddress->zip ?? ""])
@input(["name"=>"contact_name","type"=>"text","value"=>$userAddress->contact_name ?? ""])
@input(["name"=>"contact_phone","type"=>"text","value"=>$userAddress->contact_phone ?? ""])

<div class="layui-form-item layui-layout-admin">
    <div class="layui-input-block">
		<div class="layui-footer z-50" style="left:0;">
			<button class="layui-btn" lay-submit lay-filter="submit-form">{{__('submit')}}</button>
			<button type="reset" class="layui-btn layui-btn-primary">{{__('cancel')}}</button>
		</div>
    </div>
</div>

Resources/views/userAddresses/index.blade.php
@extends('core::layouts.master')

@section('content')
    <x-wd-submenu :items="
        [
            ['name' => '列表管理', 'uri' => route('user-addresses.index')]
       ]" />

    <table class="layui-hide" id="data_useraddress_table" lay-filter="data_useraddress_table"></table>
@endsection


@push('script')
    <script type="text/html" id="data_useraddress_table">
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>
    <script>
        layui.use(['table', 'element'], function(){
            var table = layui.table,
                element = layui.element;

            table.render({
                elem: '#data_useraddress_table',
                url: '{!! URL::full() !!}?orderBy=created_at&sortedBy=desc',
                page: true,
                canSearch: true,
                autoShow: '{{ route('user-addresses.show', '_id_') }}',
                height: 'full-110',
                toolbar: [],
                cellMinWidth: 80, //全局定义常规单元格的最小宽度，layui 2.2.1 新增
                cols: [[{"type":"checkbox","fixed":"left"},{"field":"id","title":"id","sort":"true","fixed":"left"},{"field":"user_id","title":"user_id"},{"field":"province","title":"province"},{"field":"city","title":"city"},{"field":"district","title":"district"},{"field":"address","title":"address"},{"field":"zip","title":"zip"},{"field":"contact_name","title":"contact_name"},{"field":"contact_phone","title":"contact_phone"},{"field":"lastused_at","title":"lastused_at"},{"field":"created_at","title":"创建时间","fixed":"right"},{"field":"updated_at","title":"更新时间","fixed":"right"},{"title":"\u64cd\u4f5c","toolbar":"#data_useraddress_table","fixed":"right","width":150}]]
            });

            //监听行工具事件
            table.on('tool(data_useraddress_table)', function(obj){
                var data = obj.data;
                console.log(obj)
                if(obj.event === 'del'){
                    layer.confirm('真的删除行么', function(index){
                        obj.del();
                        layer.close(index);
                    });
                } else if(obj.event === 'edit'){
                    layer.prompt({
                        formType: 2
                        ,value: data.email
                    }, function(value, index){
                        obj.update({
                            email: value
                        });
                        layer.close(index);
                    });
                }
            });

        });
    </script>
@endpush

Resources/views/userAddresses/show.blade.php
@extends('layouts.modal')

@section('content')
    <div class="layui-card">
		<div class="layui-card-header">详情</div>
		<div class="layui-card-body">
            <table class="layui-table">
                <tbody>
				<tr><td width=150>{{ __("field.id") }}</td><td>{!! $useraddress->id !!}</td></tr>
				<tr><td width=150>{{ __("field.user_id") }}</td><td>{!! $useraddress->user_id !!}</td></tr>
				<tr><td width=150>{{ __("field.province") }}</td><td>{!! $useraddress->province !!}</td></tr>
				<tr><td width=150>{{ __("field.city") }}</td><td>{!! $useraddress->city !!}</td></tr>
				<tr><td width=150>{{ __("field.district") }}</td><td>{!! $useraddress->district !!}</td></tr>
				<tr><td width=150>{{ __("field.address") }}</td><td>{!! $useraddress->address !!}</td></tr>
				<tr><td width=150>{{ __("field.zip") }}</td><td>{!! $useraddress->zip !!}</td></tr>
				<tr><td width=150>{{ __("field.contact_name") }}</td><td>{!! $useraddress->contact_name !!}</td></tr>
				<tr><td width=150>{{ __("field.contact_phone") }}</td><td>{!! $useraddress->contact_phone !!}</td></tr>
				<tr><td width=150>{{ __("field.lastused_at") }}</td><td>{!! $useraddress->lastused_at !!}</td></tr>
				<tr><td width=150>{{ __("field.created_at") }}</td><td>{!! $useraddress->created_at !!}</td></tr>
				<tr><td width=150>{{ __("field.updated_at") }}</td><td>{!! $useraddress->updated_at !!}</td></tr>
			</tbody>
            </table>
        </div>
    </div>
@endsection

Resources/views/userAddresses/table.blade.php
<div class="table-responsive">
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
				<th>{{ __('main.id') }}</th>
				<th>{{ __('main.user_id') }}</th>
				<th>{{ __('main.province') }}</th>
				<th>{{ __('main.city') }}</th>
				<th>{{ __('main.district') }}</th>
				<th>{{ __('main.address') }}</th>
				<th>{{ __('main.zip') }}</th>
				<th>{{ __('main.contact_name') }}</th>
				<th>{{ __('main.contact_phone') }}</th>
				<th>{{ __('main.lastused_at') }}</th>
				<th>{{ __('main.created_at') }}</th>
				<th>{{ __('main.updated_at') }}</th>
				<th><i class='fa fa-cogs'></i></th>
			</tr>
        </thead>
        <tbody>
        @foreach($userAddresses as $item)
            <tr>
				<td>{{ $item->id ?? "" }}</td>
				<td>{{ $item->user_id ?? "" }}</td>
				<td>{{ $item->province ?? "" }}</td>
				<td>{{ $item->city ?? "" }}</td>
				<td>{{ $item->district ?? "" }}</td>
				<td>{{ $item->address ?? "" }}</td>
				<td>{{ $item->zip ?? "" }}</td>
				<td>{{ $item->contact_name ?? "" }}</td>
				<td>{{ $item->contact_phone ?? "" }}</td>
				<td>{{ $item->lastused_at ?? "" }}</td>
				<td>{{ $item->created_at ?? "" }}</td>
				<td>{{ $item->updated_at ?? "" }}</td>
				<td>
					<form method="post" action="{{ route("core.user-addresses.destroy", $item->id) }}">
						<input type="hidden" name="_method" value="DELETE">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<div class="btn-group">
							<a class="btn btn-xs" title="查看" data-toggle="modal" data-position="fixed" href="{{ route("core.user-addresses.show", $item->id) }}"><i class="fa fa-eye"></i></a>
							<a class="btn btn-xs" title="编辑" data-toggle="modal" data-position="fixed" href="{{ route("core.user-addresses.edit", $item->id) }}"><i class="fa fa-edit"></i></a>
							<button type="submit" class="btn btn-xs btn-danger" onclick="return confirm('确认删除?')"><i class="fa fa-trash "></i></button>
						</div>
					</form>
				</td>
			</tr>
        @endforeach
        </tbody>
    </table>
    {{ $userAddresses->appends(request()->all())->links('__page') }}
</div>