Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Modules\Core\Http\Controllers\Auth\EmailVerificationController;
use Modules\Core\Http\Controllers\Auth\LogoutController;
use Modules\Core\Http\Controllers\DepartmentsController;
use Modules\Core\Http\Controllers\FileController;
use Modules\Core\Http\Controllers\NotificationController;
use Modules\Core\Http\Controllers\OptionsController;
use Modules\Core\Http\Controllers\PermissionsController;
use Modules\Core\Http\Controllers\RolesController;
use Modules\Core\Http\Controllers\UserAddressesController;
use Modules\Core\Http\Controllers\UsersController;
use Modules\Core\Http\Livewire\Auth\Login;
use Modules\Core\Http\Livewire\Auth\Passwords\Confirm;
use Modules\Core\Http\Livewire\Auth\Passwords\Email;
use Modules\Core\Http\Livewire\Auth\Passwords\Reset;
use Modules\Core\Http\Livewire\Auth\Register;
use Modules\Core\Http\Livewire\Auth\Verify;

Route::middleware('guest')->group(function () {
    Route::get('login', Login::class)->name('login');
    Route::get('register', Register::class)->name('register');
});

Route::get('password/reset', Email::class)->name('password.request');
Route::get('password/reset/{token}', Reset::class)->name('password.reset');

Route::middleware('admin:core')->group(function () {
    Route::get('email/verify', Verify::class)->middleware('throttle:6,1')->name('verification.notice');
    Route::get('password/confirm', Confirm::class)->name('password.confirm');
    Route::get('email/verify/{id}/{hash}', EmailVerificationController::class)->middleware('signed')->name('verification.verify');

    Route::post('logout', LogoutController::class)->name('logout');

    Route::view('/', 'core::index')->name('home');
    Route::view('/dashboard', 'core::dashboard')->name('dashboard');

    // file
    Route::get('/md', [FileController::class, 'md'])->name('file.md');

    // optios
    Route::group(['prefix' => 'option', 'as' => 'option.'], function(){

        Route::get('/', [OptionsController::class, 'index'])->name('index');
        Route::post('/', [OptionsController::class, 'store']);
    });

    // 消息管理
    Route::get('/notification', [NotificationController::class, 'index'])->name('notification.index');

    // 权限管理
    Route::post('permission/attach', [PermissionsController::class, 'attach'])->name('permission.attach');
    Route::resource('permission', PermissionsController::class);
    Route::resource('roles', RolesController::class);

    Route::match(['get', 'post'], 'users/profile', [UsersController::class, 'profile'])->name('user.profile');
    Route::match(['get', 'post'], 'users/resetpasswd', [UsersController::class, 'resetpasswd'])->name('user.resetpasswd');

    Route::resource('users', UsersController::class);
    Route::resource('departments', DepartmentsController::class);
    Route::resource('user-addresses', UserAddressesController::class);
});

Models/Permission.php
<?php

namespace Modules\Core\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Support\Collection;
use Spatie\Permission\Contracts\Permission as PermissionContract;
use Spatie\Permission\Exceptions\PermissionAlreadyExists;
use Spatie\Permission\Exceptions\PermissionDoesNotExist;
use Spatie\Permission\Guard;
use Spatie\Permission\PermissionRegistrar;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Traits\RefreshesPermissionCache;
use Stancl\Tenancy\Database\Concerns\BelongsToTenant;

class Permission extends Model implements PermissionContract
{
    use HasRoles;
    use BelongsToTenant;
    use RefreshesPermissionCache;

    protected $fillable = ['label', 'name', 'guard_name', 'tenant_id'];

    public function __construct(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? config('auth.defaults.guard');

        parent::__construct($attributes);

        $this->setTable(config('permission.table_names.permissions'));
    }

    public static function create(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? Guard::getDefaultName(static::class);

        $permission = static::getPermissions(['name' => $attributes['name'], 'guard_name' => $attributes['guard_name']])->first();

        if ($permission) {
            throw PermissionAlreadyExists::create($attributes['name'], $attributes['guard_name']);
        }

        return static::query()->create($attributes);
    }

    /**
     * A permission can be applied to roles.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(
            config('permission.models.role'),
            config('permission.table_names.role_has_permissions'),
            'permission_id',
            'role_id'
        );
    }

    /**
     * A permission belongs to some users of the model associated with its guard.
     */
    public function users(): MorphToMany
    {
        return $this->morphedByMany(
            getModelForGuard($this->attributes['guard_name']),
            'model',
            config('permission.table_names.model_has_permissions'),
            'permission_id',
            config('permission.column_names.model_morph_key')
        );
    }

    /**
     * Find a permission by its name (and optionally guardName).
     *
     * @param string $name
     * @param string|null $guardName
     *
     * @throws \Spatie\Permission\Exceptions\PermissionDoesNotExist
     *
     * @return \Spatie\Permission\Contracts\Permission
     */
    public static function findByName(string $name, $guardName = null): PermissionContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);
        $permission = static::getPermissions(['name' => $name, 'guard_name' => $guardName])->first();
        if (! $permission) {
            throw PermissionDoesNotExist::create($name, $guardName);
        }

        return $permission;
    }

    /**
     * Find a permission by its id (and optionally guardName).
     *
     * @param int $id
     * @param string|null $guardName
     *
     * @throws \Spatie\Permission\Exceptions\PermissionDoesNotExist
     *
     * @return \Spatie\Permission\Contracts\Permission
     */
    public static function findById(int $id, $guardName = null): PermissionContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);
        $permission = static::getPermissions(['id' => $id, 'guard_name' => $guardName])->first();

        if (! $permission) {
            throw PermissionDoesNotExist::withId($id, $guardName);
        }

        return $permission;
    }

    /**
     * Find or create permission by its name (and optionally guardName).
     *
     * @param string $name
     * @param string|null $guardName
     *
     * @return \Spatie\Permission\Contracts\Permission
     */
    public static function findOrCreate(string $name, $guardName = null): PermissionContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);
        $permission = static::getPermissions(['name' => $name, 'guard_name' => $guardName])->first();

        if (! $permission) {
            return static::query()->create(['name' => $name, 'guard_name' => $guardName]);
        }

        return $permission;
    }

    /**
     * Get the current cached permissions.
     */
    protected static function getPermissions(array $params = []): Collection
    {
        return app(PermissionRegistrar::class)->getPermissions($params);
    }

    /**
     * @param $query
     * @param $type
     * @return mixed
     */
    public function scopeType($query, $type)
    {
        return $query->where('type', $type);
    }

}

Http/Controllers/PermissionsController.php
<?php

namespace Modules\Core\Http\Controllers;

use Modules\Core\Http\Controllers\BaseController;
use Illuminate\Http\Request;
use Modules\Core\Models\Role;
use Modules\Core\Models\Permission;
use Modules\Core\Http\Requests\PermissionRequest;

/**
 * Class PermissionsController.
 *
 * @package namespace Modules\Core\Http\Controllers;
 */
class PermissionsController extends BaseController
{
    /**
     * @var Permission
     */
    protected $model;

    public function __construct(Permission $model)
    {
        $this->model = $model;
    }


    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index(Request $request)
    {
        $role_id = $request->get('role_id');
        $role = $role_id?Role::findOrFail($role_id):Role::first();
        $role_guard = isset($role)?$role->guard_name:'web';
        return view('core::permissions.index', compact('role', 'role_guard'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        // $this->authorize('create', Permission::class);
        return view('core::permissions.create');
    }


    /**
     * @param PermissionRequest $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function store(PermissionRequest $request)
    {
        try {
            $this->model->create($request->all());

            return redirect()->back()->with('status', 'create success');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $permission = $this->model->find($id);
        // $this->authorize('view', $permission);
        return $this->toTable($permission);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = $this->model->find($id);
        // $this->authorize('update', $permission);

        return view('core::permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  PermissionUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *

     */
    public function update(PermissionRequest $request, $id)
    {
        try {
            $model = $this->model->find($id);
            // $this->authorize('update', $model);

            $model->fill($request->all())->save();
            return redirect()->back()->with('status', 'update success');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);
        // $this->authorize('delete', $model);
        $model->delete();

        return $this->toResponse([], '删除成功');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function attach(Request $request)
    {
        $request->validate(['role_id' => 'required']);

        $role = Role::find($request->get('role_id'));

        $role->permissions()->detach();
        $role->permissions()->attach($request->get('permission'));

        return redirect()->back()->with('status', 'save success');
    }
}

Resources/views/permissions/create.blade.php
@extends('core::layouts.master')

@section('content')
    <div class="layui-card">
        <div class="layui-card-header">新增</div>
        <div class="layui-card-body">
            <x-wd-form :action="route('permission.store')" method="post">

                <div class="layui-row layui-col-space10">
                    @include('core::permissions.fields')
                </div>

            </x-form>
        </div>
    </div>
@endsection

Resources/views/permissions/edit.blade.php
@extends('core::layouts.master')

@section('content')
	<div class="layui-card layui-form">
		<div class="layui-card-header">编辑#{{ $permission->id }}</div>
		<div class="layui-card-body">
            <x-wd-form :action="route('permission.update', $permission->id)" method="patch">

				<div class="layui-row layui-col-space10 layui-form-item">
					@include('core::permissions.fields')
				</div>

			</x-form>
		</div>
	</div>
@endsection

Resources/views/permissions/fields.blade.php
<x-wd-formItem label="name">
<x-wd-input name="name" required :value="$permission->name??''"/>
</x-wd-formItem>

<x-wd-formItem label="label">
<x-wd-input name="label" required :value="$permission->name??''"/>
</x-wd-formItem>

<x-wd-formItem label="guard_name">
<x-wd-input.select name="guard_name" required :options="['web' => 'web', 'org' => 'org']" :value="$permission->guard_name??'web'" />
</x-wd-formItem>

<div class="layui-form-item layui-layout-admin">
    <div class="layui-input-block">
		<div class="layui-footer z-50" style="left:0;">
			<button class="layui-btn" lay-submit lay-filter="component-form-demo1">{{__('submit')}}</button>
			<button type="reset" class="layui-btn layui-btn-primary">{{__('cancel')}}</button>
		</div>
    </div>
</div>

@push('script')
	<script>
		layui.use('form', function(){
			var form = layui.form
		})
	</script>
@endpush

Resources/views/permissions/index.blade.php
@extends('core::layouts.column_left')

@section('leftside')
    <div class="layui-card">
        <div class="layui-card-header">
            <a lay-href="{{ route('roles.create') }}" class="border px-4  py-1 text-sm leading-tight mt-4">添加角色</a>
            <a lay-href="{{ route('permission.create') }}" class="border px-4  py-1 text-sm leading-tight mt-4">添加权限</a>
        </div>
        <div class="layui-card-body">
            <h3 class="p-2 bg-gray-200 font-bold">人员角色</h3>
            <ul>
                @foreach(\Modules\Core\Models\Role::nosuper()->where('guard_name', 'web')->get() as $_role)
                    <li><a href="{{ route('permission.index', ['role_id' => $_role->id]) }}" class="{{ $_role['id']==$role->id?'text-red-500':'' }}">{{ $_role['label'] }}</a></li>
                @endforeach
            </ul>
            <h3 class="p-2 bg-gray-200 font-bold mt-4">运营商</h3>
            <ul>
                @foreach(\Modules\Core\Models\Role::where('guard_name', 'org')->get() as $_role)
                    <li><a href="{{ route('permission.index', ['role_id' => $_role->id]) }}" class="{{ $_role['id']==$role->id?'text-red-500':'' }}">{{ $_role['label'] }}</a></li>
                @endforeach
            </ul>
        </div>
    </div>

@stop

@section('content')
    <x-wd-submenu :items="
        [
            ['name' => '列表管理', 'uri' => route('permission.index')]
       ]" />

    <x-wd-card>
        <x-wd-form :action="route('permission.attach')" method="post">
            <dl class="p-lg">
                @foreach(\Modules\Core\Models\Permission::where('guard_name', $role_guard)->get() as $permiss)
                    <dd class="mb-2">
                        <label for="permission_{{ $permiss['id'] }}" class="m-r-lg"></label>
                        <input type="checkbox" name="permission[]" id="permission_{{ $permiss['id'] }}"
                        value="{{ $permiss['id'] }}"
                        {{ isset($role)&&$role->checkPermissionTo($permiss['name'])?'checked':'' }}
                        data-name="{{ $permiss['name'] }}">{{ $permiss['label'] }}
                    </dd>
                @endforeach
            </dl>

            <x-wd-formItem type="submit">
                <button class="layui-btn" lay-submit lay-filter="component-form-demo1">{{__('submit')}}</button>
            </x-wd-formItem>

            <input type="hidden" name="role_id" value="{{ $role->id ?? '' }}">
        </x-form>
    </x-card>



@endsection


@push('script')
    <script>
        layui.use(['table'], function(){
            var table = layui.table,
                admin = parent.layui == layui?layui.admin:parent.layui.admin,
                $department_tree = $("#depart_tree");

            table.render({
                elem: '#data_permission_table',
                url: '{!! URL::full() !!}',
                autoShow: '{{ route('permission.show', '_id_') }}',
                where: {'orderBy': 'created_at', 'sortedBy': 'desc'},
                page: true,
                canSearch: true,
                toolbar: 'default',
                height: 'full-110',
                cellMinWidth: 80,
                cols: [[{"type":"checkbox","fixed":"left"},{"field":"id","title":"id","sort":"true","fixed":"left","width":"120"},{"field":"name","title":"name"},{"field":"guard_name","title":"guard_name"},{"field":"created_at","title":"创建时间"},{"field":"updated_at","title":"更新时间","fixed":"right"}]]
            });

            //监听行工具事件
            table.on('toolbar(data_permission_table)', function(obj){
                var checked = table.checkStatus('data_permission_table');

                if(obj.event == 'create') {
                    admin.openTab('{{ route('permission.create') }}', '新增数据')
                    return true;
                }

                if((obj.event == 'delete'|| obj.event == 'update') && checked.data.length >0 ) {
                    if(checked.data.length !== 1) {
                        layer.msg('请选择一条数据!');
                        return false;
                    }

                    if(obj.event === 'delete') {
                        layer.confirm('真的删除行么', function(index){
                            parent.layui.lumina.request.post('{{ route('permission.destroy', '_id_') }}'.replace('_id_', checked.data[0].id), {'_method': 'DELETE'}, function(res){
                                layer.msg('删除成功');
                                table.reload('data_permission_table')
                            })

                            layer.close(index);
                        });
                    }else if(obj.event === 'update') {
                        parent.layui.lumina.openTab('{{route('permission.edit', '_id_')}}'.replace('_id_', checked.data[0].id), '修改数据#'+checked.data[0].id)
                        return true;
                    }
                }
            });

        });
    </script>
@endpush