Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Modules\Core\Http\Controllers\Auth\EmailVerificationController;
use Modules\Core\Http\Controllers\Auth\LogoutController;
use Modules\Core\Http\Controllers\DepartmentsController;
use Modules\Core\Http\Controllers\FileController;
use Modules\Core\Http\Controllers\NotificationController;
use Modules\Core\Http\Controllers\OptionsController;
use Modules\Core\Http\Controllers\PermissionsController;
use Modules\Core\Http\Controllers\RolesController;
use Modules\Core\Http\Controllers\UserAddressesController;
use Modules\Core\Http\Controllers\UsersController;
use Modules\Core\Http\Livewire\Auth\Login;
use Modules\Core\Http\Livewire\Auth\Passwords\Confirm;
use Modules\Core\Http\Livewire\Auth\Passwords\Email;
use Modules\Core\Http\Livewire\Auth\Passwords\Reset;
use Modules\Core\Http\Livewire\Auth\Register;
use Modules\Core\Http\Livewire\Auth\Verify;

Route::middleware('guest')->group(function () {
    Route::get('login', Login::class)->name('login');
    Route::get('register', Register::class)->name('register');
});

Route::get('password/reset', Email::class)->name('password.request');
Route::get('password/reset/{token}', Reset::class)->name('password.reset');

Route::middleware('admin:core')->group(function () {
    Route::get('email/verify', Verify::class)->middleware('throttle:6,1')->name('verification.notice');
    Route::get('password/confirm', Confirm::class)->name('password.confirm');
    Route::get('email/verify/{id}/{hash}', EmailVerificationController::class)->middleware('signed')->name('verification.verify');

    Route::post('logout', LogoutController::class)->name('logout');

    Route::view('/', 'core::index')->name('home');
    Route::view('/dashboard', 'core::dashboard')->name('dashboard');

    // file
    Route::get('/md', [FileController::class, 'md'])->name('file.md');

    // optios
    Route::group(['prefix' => 'option', 'as' => 'option.'], function(){

        Route::get('/', [OptionsController::class, 'index'])->name('index');
        Route::post('/', [OptionsController::class, 'store']);
    });

    // 消息管理
    Route::get('/notification', [NotificationController::class, 'index'])->name('notification.index');

    // 权限管理
    Route::post('permission/attach', [PermissionsController::class, 'attach'])->name('permission.attach');
    Route::resource('permission', PermissionsController::class);
    Route::resource('roles', RolesController::class);

    Route::match(['get', 'post'], 'users/profile', [UsersController::class, 'profile'])->name('user.profile');
    Route::match(['get', 'post'], 'users/resetpasswd', [UsersController::class, 'resetpasswd'])->name('user.resetpasswd');

    Route::resource('users', UsersController::class);
    Route::resource('departments', DepartmentsController::class);
    Route::resource('user-addresses', UserAddressesController::class);
});

Models/Role.php
<?php

namespace Modules\Core\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Spatie\Permission\Contracts\Role as RoleContract;
use Spatie\Permission\Exceptions\GuardDoesNotMatch;
use Spatie\Permission\Exceptions\RoleAlreadyExists;
use Spatie\Permission\Exceptions\RoleDoesNotExist;
use Spatie\Permission\Guard;
use Spatie\Permission\Traits\HasPermissions;
use Spatie\Permission\Traits\RefreshesPermissionCache;
use Stancl\Tenancy\Database\Concerns\BelongsToTenant;

class Role extends Model implements RoleContract
{
    use HasPermissions;
    use BelongsToTenant;
    use RefreshesPermissionCache;


    protected $fillable = ['name', 'label', 'roleid', 'platform', 'guard_name', 'tenant_id'];

    public function __construct(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? config('auth.defaults.guard');

        parent::__construct($attributes);

        $this->setTable(config('permission.table_names.roles'));
    }

    /**
     * @param array $attributes
     * @return \Illuminate\Database\Eloquent\Builder|Model
     */
    public static function create(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? Guard::getDefaultName(static::class);

       if (static::where([
            'name' => $attributes['name'],
            'guard_name' => $attributes['guard_name'],
            'tenant_id' => $attributes['tenant_id'] ?? tenant('id')
        ])->first()) {
            throw RoleAlreadyExists::create($attributes['name'], $attributes['guard_name']);
        }
        return static::query()->create($attributes);
    }

    /**
     * A role may be given various permissions.
     */
    public function permissions(): BelongsToMany
    {
        return $this->belongsToMany(
            config('permission.models.permission'),
            config('permission.table_names.role_has_permissions'),
            'role_id',
            'permission_id'
        );
    }

    /**
     * A role belongs to some users of the model associated with its guard.
     */
    public function users(): MorphToMany
    {
        return $this->morphedByMany(
            getModelForGuard($this->attributes['guard_name']),
            'model',
            config('permission.table_names.model_has_roles'),
            'role_id',
            config('permission.column_names.model_morph_key')
        );
    }

    /**
     * Find a role by its name and guard name.
     *
     * @param string $name
     * @param string|null $guardName
     *
     * @return \Spatie\Permission\Contracts\Role|\Spatie\Permission\Models\Role
     *
     * @throws \Spatie\Permission\Exceptions\RoleDoesNotExist
     */
    public static function findByName(string $name, $guardName = null): RoleContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);

        $role = static::where('name', $name)->where('guard_name', $guardName)->first();

        if (! $role) {
            throw RoleDoesNotExist::named($name);
        }

        return $role;
    }

    public static function findById(int $id, $guardName = null): RoleContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);

        $role = static::where('id', $id)->where('guard_name', $guardName)->first();

        if (! $role) {
            throw RoleDoesNotExist::withId($id);
        }

        return $role;
    }

    /**
     * Find or create role by its name (and optionally guardName).
     *
     * @param string $name
     * @param string|null $guardName
     *
     * @return \Spatie\Permission\Contracts\Role
     */
    public static function findOrCreate(string $name, $guardName = null): RoleContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);

        $role = static::where('name', $name)->where('guard_name', $guardName)->first();

        if (! $role) {
            return static::query()->create(['name' => $name, 'guard_name' => $guardName]);
        }

        return $role;
    }

    /**
     * Determine if the user may perform the given permission.
     *
     * @param string|Permission $permission
     *
     * @return bool
     *
     * @throws \Spatie\Permission\Exceptions\GuardDoesNotMatch
     */
    public function hasPermissionTo($permission): bool
    {
        $permissionClass = $this->getPermissionClass();

        if (is_string($permission)) {
            $permission = $permissionClass->findByName($permission, $this->getDefaultGuardName());
        }

        if (is_int($permission)) {
            $permission = $permissionClass->findById($permission, $this->getDefaultGuardName());
        }

        if (! $this->getGuardNames()->contains($permission->guard_name)) {
            throw GuardDoesNotMatch::create($permission->guard_name, $this->getGuardNames());
        }

        return $this->permissions->contains('id', $permission->id);
    }


    /**
     * @param int $level
     * @param string $type
     * @return mixed
     */
    public static function getTree($level = 1, $guard_name = 'web')
    {
        return self::where('guard_name', $guard_name)->where('name', '<>', 'SUPER')->get()->each(function($item, $key) use($level) {
            $item['text'] =  $item['label'];
            $item['state'] = ['opened'=> $item['level'] <= $level?true:false];
        });
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeNosuper($query)
    {
        return $query->where('name', '<>', 'SUPER');
    }

}

Http/Controllers/Api/RolesController.php
<?php
/**
 * Created by PhpStorm.
 * User: jory
 * Date: 2019/4/3
 * Time: 18:21
 */

namespace Modules\Core\Http\Controllers\Api;


use Illuminate\Http\Request;
use Modules\Core\Http\Controllers\BaseController;
use Modules\Core\Models\Role;
use Modules\Core\Models\User;

class RolesController extends BaseController
{

    protected $model;

    /**
     * UsersController constructor.
     * @param UserRepository $model
     */
    public function __construct(Role $model)
    {
        $this->model = $model;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function attach(Request $request)
    {
        $request->validate(['role_id'=>'required', 'ids' =>'required']);

        try{
            $role = $this->model->find($request->get('role_id'));
            foreach (explode(',', $request->get('ids')) as $_id) {
                $_user = User::find($_id);
                $_user->assignRole($role);
            }
            return $this->toResponse([], 'success');
        }catch (\Exception $e){
            return $this->toException($e);
        }
    }

    public function detach(Request $request)
    {
        $request->validate(['role_id'=>'required', 'ids' =>'required']);

        try{
            $role = $this->model->find($request->get('role_id'));
            foreach (explode(',', $request->get('ids')) as $_id) {
                $_user = User::find($_id);
                $_user->removeRole($role);
            }
            return $this->toResponse([], 'success');
        }catch (\Exception $e){
            return $this->toException($e);
        }
    }
}

Http/Controllers/RolesController.php
<?php

namespace Modules\Core\Http\Controllers;

use Modules\Core\Http\Controllers\BaseController;
use Illuminate\Http\Request;
use Modules\Core\Models\Role;
use Modules\Core\Http\Requests\RoleRequest;
use Modules\Core\Http\Resources\RoleResource;
use Illuminate\Validation\ValidationException;
use Modules\Core\Models\Repositories\RoleRepository;

/**
 * Class RolesController.
 *
 * @package namespace Modules\Core\Http\Controllers;
 */
class RolesController extends BaseController
{
    /**
     * @var Role
     */
    protected $model;

    public function __construct(Role $model)
    {
        $this->model = $model;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|mixed
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function index(Request $request)
    {
        if($request->expectsJson()) {
            $roles = $this->model->paginate($request->get('limit', 15));
            return $this->toCollection($roles, RoleResource::class);
        }
        return view('core::roles.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        // $this->authorize('create', Role::class);
        return view('core::roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  RoleCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *

     */
    public function store(RoleRequest $request)
    {
        try {
            $this->model->create($request->all());

            return redirect()->back()->with('status', 'create success');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = $this->model->find($id);
        // $this->authorize('view', $role);
        return $this->toTable($role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = $this->model->find($id);
        // $this->authorize('update', $role);

        return view('core::roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  RoleUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *

     */
    public function update(RoleRequest $request, $id)
    {
        try {
            $model = $this->model->find($id);
            // $this->authorize('update', $model);

            $model->fill($request->all())->save();

            return redirect()->back()->with('status', 'update success');
        } catch (ValidationException $e) {
            return $this->toException($e);
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);
        // $this->authorize('delete', $model);
        $model->delete($id);

        return $this->toResponse([], '删除成功');
    }
}

Resources/views/roles/create.blade.php
@extends('core::layouts.master')

@section('content')
    <div class="layui-card">
        <div class="layui-card-header">新增</div>
        <div class="layui-card-body">
            <x-wd-form :action="route('roles.store')" method="post">


                <div class="layui-row layui-col-space10">
                    @include('core::roles.fields')
                </div>

            </x-form>
        </div>
    </div>
@endsection

Resources/views/roles/edit.blade.php
@extends('core::layouts.master')

@section('content')
	<div class="layui-card layui-form">
		<div class="layui-card-header">编辑#{{ $role->id }}</div>
		<div class="layui-card-body">
            <x-wd-form :action="route('roles.update', $role->id)" method="patch">

				<div class="layui-row layui-col-space10 layui-form-item">
					@include('core::roles.fields')
				</div>

			</x-form>
		</div>
	</div>
@endsection

Resources/views/roles/fields.blade.php
<x-wd-formItem label="name">
<x-wd-input name="name" :value="$role->name??''"/>
</x-wd-formItem>

<x-wd-formItem label="label">
<x-wd-input name="label" :value="$role->label??''"/>
</x-wd-formItem>

<x-wd-formItem label="guard_name">
<x-wd-input.select name="guard_name" required :options="['web']" :value="$permission->guard_name??'web'" />
</x-wd-formItem>


<div class="layui-form-item layui-layout-admin">
    <div class="layui-input-block">
		<div class="layui-footer z-50" style="left:0;">
			<button class="layui-btn" lay-submit lay-filter="component-form-demo1">{{__('submit')}}</button>
			<button type="reset" class="layui-btn layui-btn-primary">{{__('cancel')}}</button>
		</div>
    </div>
</div>

@push('script')
	<script>
		layui.use('form', function(){
			var form = layui.form
		})
	</script>
@endpush

Resources/views/roles/index.blade.php
@extends('core::layouts.master')

@section('content')
    <x-wd-submenu :items="
        [
            ['name' => '列表管理', 'uri' => route('roles.index')]
       ]" />

    <table class="layui-hide" id="data_role_table" lay-filter="data_role_table"></table>
@endsection


@push('script')
    <script>
        layui.use(['table', 'element'], function(){
            var table = layui.table,
                element = layui.element;

            table.render({
                elem: '#data_role_table',
                url: '{!! URL::full() !!}',
                autoShow: '{{ route('roles.show', '_id_') }}',
                where: {'orderBy': 'created_at', 'sortedBy': 'desc'},
                page: true,
                canSearch: true,
                toolbar: 'default',
                height: 'full-110',
                cellMinWidth: 80,
                cols: [[{"type":"checkbox","fixed":"left"},{"field":"id","title":"id","sort":"true","fixed":"left","width":"120"},{"field":"name","title":"name"},{"field":"guard_name","title":"guard_name"},{"field":"created_at","title":"创建时间"},{"field":"updated_at","title":"更新时间","fixed":"right"}]]
            });

            //监听行工具事件
            table.on('toolbar(data_role_table)', function(obj){
                var checked = table.checkStatus('data_role_table');

                if(obj.event == 'create') {
                    parent.layui.lumina.openTab('{{ route('roles.create') }}', '新增数据')
                    return true;
                }

                if((obj.event == 'delete'|| obj.event == 'update') && checked.data.length >0 ) {
                    if(checked.data.length !== 1) {
                        layer.msg('请选择一条数据!');
                        return false;
                    }

                    if(obj.event === 'delete') {
                        layer.confirm('真的删除行么', function(index){
                            parent.layui.lumina.request.post('{{ route('roles.destroy', '_id_') }}'.replace('_id_', checked.data[0].id), {'_method': 'DELETE'}, function(res){
                                layer.msg('删除成功');
                                table.reload('data_role_table')
                            })

                            layer.close(index);
                        });
                    }else if(obj.event === 'update') {
                        parent.layui.lumina.openTab('{{route('roles.edit', '_id_')}}'.replace('_id_', checked.data[0].id), '修改数据#'+checked.data[0].id)
                        return true;
                    }
                }
            });

        });
    </script>
@endpush